image: python:3.6.0

pages:
  script:
  - apt-get install python3-dev python3-setuptools
  - apt-get install libtiff5-dev libjpeg8-dev zlib1g-dev
  - apt-get install libfreetype6-dev liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev python-tk
  - pip install nikola
  - nikola build
  artifacts:
    paths:
    - public
  only:
  - master